### PR TITLE
Update for app release v0.395.0

### PR DESCRIPTION
**Pull request by katthartic**
- Remove out-of-date pages
- Update all references to project

### CODE REVIEW

**Comment by katthartic** [comment]
@blakeburch The images in `Great Expectations` are incorrect since they still reference a Vessel and an old Fleet log. I can update these but I wasn't sure where to add images now.

**Comment by blakeburch** [comment]
I wouldn't worry about it for now.

Most images are still housed in docusaurus.

**Comment by blakeburch** [comment]
Under something like assets/gitbook or gitbook/assets

**Comment by katthartic** [comment]
<!here> Anyone able to review/approve this before EOD today? I want to get it out before the break.

**Review by blakeburch — APPROVED** [review]

**Pull request merged**
