### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by forstmeier**

### CODE REVIEW

**Review by blakeburch — APPROVED** [review]

**Comment by katthartic** [comment]
@blakeburch Doing a little extra testing and I just noticed is that while the handle bars make re-ordering more obvious, once you have re-ordered you can't save. You have to make some other edit to actually save it. Perhaps we should not mention the handle bars for now and I can look into a fix for the saving?

**Comment by forstmeier** [comment]
Also, we may want to relax the restriction on this repo where @ericelsken needs to approve every change.

**Comment by blakeburch** [comment]
Go ahead and mention them, but yes @katthartic if that’s an issue (didn’t test for that) it will need a fix.

**Comment by blakeburch** [comment]
Removed him. You can merge.

**Comment by blakeburch** [comment]
*Removed the permission requirement that the approval must be him.

**Pull request merged**
