### PR TITLE
Update change log for Release v0.297

### PR DESCRIPTION
**Pull request by katthartic**

### CODE REVIEW

**Comment by katthartic** [comment]
@forstmeier Mind taking a quick look at this for me? It is the documentation update for the latest release.

**Comment by forstmeier** [comment]
Just confirming that we want the date in the changelog to be 20th not today the 22nd?

**Comment by katthartic** [comment]
The release went out on the 20th... so, I'm not sure.

**Review by forstmeier — APPROVED** [review]

**Comment by forstmeier** [comment]
Probably best for that day then.

**Pull request merged**
